
package br.com.companhiadesistemas.googleappsserviceprovider.entities;

import java.util.*;
import org.springframework.ldap.odm.annotations.*;

/**
* Generated by Spring LDAP ODM to represent the LDAP object classes:
* <ul>
* <li>top</li>
* <li>ergoogleappsorgunit</li>
* </ul>
*/
@Deprecated
@Entry(objectClasses={"top", "ergoogleappsorgunit"})
public final class GoogleAppsOrgUnit {


   static final String UID_ATTRIBUTE = "googleorgunitpath"; 
   @Attribute(name="objectClass", syntax="1.3.6.1.4.1.1466.115.121.1.38")
   private List<String> objectClass=new ArrayList<String>(
		   Arrays.asList("top", "ergoogleappsorgunit")
		   );

   @Attribute(name="googleorgunitdescription", syntax="1.3.6.1.4.1.1466.115.121.1.15")
   private String googleorgunitdescription;

   @Attribute(name="googleorgunitblockinheritance", syntax="1.3.6.1.4.1.1466.115.121.1.15")
   private List<String> googleorgunitblockinheritance=new ArrayList<String>();

   @Attribute(name="googleorgunitname", syntax="1.3.6.1.4.1.1466.115.121.1.15")
   private String googleorgunitname;

   @Attribute(name="googleorgunitpath", syntax="1.3.6.1.4.1.1466.115.121.1.15")
   private String googleorgunitpath;

   @Attribute(name="googleorgunit", syntax="1.3.6.1.4.1.1466.115.121.1.15")
   private String googleorgunit;
   
   public String getDn() {
      return UID_ATTRIBUTE+"="+googleorgunitpath;
   }

   public void setDn(String dn) {
   }

   public String getGoogleorgunitdescription() {
      return googleorgunitdescription;
   }

   public void setGoogleorgunitdescription(String googleorgunitdescription) {
      this.googleorgunitdescription=googleorgunitdescription;
   }
   public void addGoogleorgunitblockinheritance(String googleorgunitblockinheritance) {
      this.googleorgunitblockinheritance.add(googleorgunitblockinheritance);
   }

   public List<String> getObjectClass() {
	return objectClass;
   }

   public void setObjectClass(List<String> objectClass) {
	this.objectClass = objectClass;
   }

   public void removeGoogleorgunitblockinheritance(String googleorgunitblockinheritance) {
      this.googleorgunitblockinheritance.remove(googleorgunitblockinheritance);
   }

   public Iterator<String> getGoogleorgunitblockinheritanceIterator() {
      return googleorgunitblockinheritance.iterator();
   }

   public String getGoogleorgunitname() {
      return googleorgunitname;
   }

   public void setGoogleorgunitname(String googleorgunitname) {
      this.googleorgunitname=googleorgunitname;
   }
   public String getGoogleorgunitpath() {
      return googleorgunitpath;
   }

   public void setGoogleorgunitpath(String googleorgunitpath) {
      this.googleorgunitpath=googleorgunitpath;
   }
   public String getGoogleorgunit() {
      return googleorgunit;
   }

   public void setGoogleorgunit(String googleorgunit) {
      this.googleorgunit=googleorgunit;
   }
}


